version: "3.8"

services:
  social-ui-dev:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    container_name: social-ui-dev
    image: social-ui-dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
